### ISSUE TITLE
Portals of Praevus MDL format unrecognized.

### ISSUE THREAD

**Issue by ShinyMetagross** [victorfeitosa/hexen2-mdl-export-import#3]
Description:
Almost all Portals of Praevus MDL files cannot be imported into Blender 2.82. These MDL files have a value for _ident_ of RAPO2, whereas standard Hexen II and Quake MDL files use IDPO.

Examples of models that cannot be imported from pak3.pak include:
pravus.mdl
yakman.mdl
snowleopard.mdl
imp.mdl
archer2.mdl
samurai.mdl
fangel.mdl
pent.mdl

![error](https://user-images.githubusercontent.com/30511800/89351208-648a1280-d666-11ea-8539-cd4e9681a5b8.jpg)

**Comment by victorfeitosa** [comment]
Alright, I identified the issue and I have a solution in mind. I'll try to work on it soon enough

**Comment by victorfeitosa** [comment]
Fixed
![image](https://user-images.githubusercontent.com/8713845/91241229-47e77480-e712-11ea-820e-e08c703c8bb4.png)
